name: Build Docker image

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/jonko0493/clangd
        labels: |
          org.opencontainers.image.authors=jonko0493
          org.opencontainers.image.vendor=jonko0493
          org.opencontainers.image.title=clangd Docker image
          org.opencontainers.image.description=Base docker image with clangd binary
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}